lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
url: https://blog.hirokuma.work
title: hiro99ma blog
description: 何か技術的なこと
google_analytics: G-552KB5LZK4
show_downloads: false
theme: jekyll-theme-hacker
